# Generated by Django 4.1.5 on 2023-12-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagementToolApp', '0002_teht'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kurssi',
            options={'verbose_name_plural': 'Kurssit'},
        ),
        migrations.AlterModelOptions(
            name='teht',
            options={'verbose_name_plural': 'Tehtavat'},
        ),
    ]
