# Generated by Django 4.1.5 on 2023-12-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagementToolApp', '0003_alter_kurssi_options_alter_teht_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurssi',
            name='dedis',
            field=models.DateTimeField(null=True),
        ),
    ]
