# Generated by Django 4.1.5 on 2023-12-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagementToolApp', '0004_kurssi_dedis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurssi',
            name='dedis',
        ),
        migrations.AddField(
            model_name='teht',
            name='dedis',
            field=models.DateTimeField(null=True),
        ),
    ]
