# Generated by Django 4.1.6 on 2023-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagementToolApp', '0005_remove_kurssi_dedis_teht_dedis'),
    ]

    operations = [
        migrations.AddField(
            model_name='teht',
            name='valmis',
            field=models.BooleanField(null=True),
        ),
    ]
