# Generated by Django 4.1.5 on 2023-12-13 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TimeManagementToolApp', '0006_teht_valmis'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurssi',
            name='kayttaja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
